name: nightly
on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  docker:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GIT_TOKEN }}
    - name: Set up Java 16
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 16
    - name: Build with Maven
      run: |
        git clone https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN }}@github.com/stellartrails/desktop
        cd desktop
        mvn -B -DskipTests -DskipITs -ntp package
